## Original Database
DOCUMENTS_DIR:
STOPWORD_FILE_DIR:


## BM25-Related
BM25_SEGS_DIR:
BM25_SEGS_INFO:
BM25_SEGS_INDEX_DIR:
BM25_SPLIT:
BM25_INDEX:
# doc2segs
N_SENT:
N_OVERLAP:
# pyserini.index
INDEX_THREADS:
# pyserini.search
SEARCH_K:
SEARCH_THREADS:
# Recall
RECALL_NUM_HITS:


## DPR-Related
DPR_SEGS_DIR:
DPR_SEGS_INFO:
DPR_SEGS_EMBS_DIR:
DPR_MODEL_DIR:
DPR_SPLIT:
DPR_EMBED:
EMBEDDING_BATCHSIZE:
EMBEDDING_DEVICE:
# doc2segs
MAX_LENGTH:
MIN_OVERLAP:
# Search
SEARCH_NUM_HITS:
