## Original Database
DOCUMENTS_DIR: /Documents/LCRdatabase/original
STOPWORD_FILE_DIR: src/stopwords/


## BM25-Related
BM25_SEGS_DIR: /Documents/LCRdatabase/segs/bm25/
BM25_SEGS_INFO: /Documents/LCRdatabase/segs/bm25_info.json
BM25_SEGS_INDEX_DIR: /Documents/LCRdatabase/pyserini_index/
BM25_SPLIT: True
BM25_INDEX: True
# doc2segs
N_SENT: 10
N_OVERLAP: 5
# pyserini.index
INDEX_THREADS: 8
# pyserini.search
SEARCH_K: 1500
SEARCH_THREADS: 8
# Recall
RECALL_NUM_HITS: 200


## DPR-Related
DPR_SEGS_DIR: /Documents/LCRdatabase/segs/dpr/
DPR_SEGS_INFO: /Documents/LCRdatabase/segs/dpr_info.json
DPR_SEGS_EMBS_DIR: /Documents/LCRdatabase/dpr_embedding/
DPR_MODEL_DIR: models/trained_model/ckpt-0322-step11520
DPR_SPLIT: True
DPR_EMBED: True
EMBEDDING_DEVICE: cuda
# doc2segs
MAX_LENGTH: 512
MIN_OVERLAP: 128
# Search
SEARCH_NUM_HITS: 30
